FROM alpine:3.23

RUN apk update && \
    apk upgrade && \
    apk add --no-cache \
      bash \
      git \
      curl \
      openssh \
      docker \
      yq \
      helm \
      github-cli

RUN apk add --no-cache nodejs npm

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"


RUN npm i -g pnpm@10.22.0

RUN pnpm config set network-timeout 600000 && \
    pnpm config set fetch-retries 5 && \
    pnpm config set network-concurrency 3

WORKDIR /app

COPY . .

RUN pnpm install --frozen-lockfile